In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import BaggingClassifier
from sklearn import metrics
from sklearn.metrics import confusion_matrix, accuracy_score
from tkinter import *

In [2]:
nasa_data = pd.read_csv('Downloads/nasa_dataset.csv')

In [3]:
nasa_data

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9559,9560,10031643,K07984.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,0,0,...,-152.0,4.296,0.231,-0.189,1.088,0.313,-0.228,298.74921,46.973351,14.478
9560,9561,10090151,K07985.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,1,...,-166.0,4.529,0.035,-0.196,0.903,0.237,-0.079,297.18875,47.093819,14.082
9561,9562,10128825,K07986.01,NaN,CANDIDATE,CANDIDATE,0.497,0,0,0,...,-220.0,4.444,0.056,-0.224,1.031,0.341,-0.114,286.50937,47.163219,14.757
9562,9563,10147276,K07987.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.021,0,0,1,...,-236.0,4.447,0.056,-0.224,1.041,0.341,-0.114,294.16489,47.176281,15.385
9563,9564,10156110,K07989.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,0,1,...,-225.0,4.385,0.054,-0.216,1.193,0.410,-0.137,297.00977,47.121021,14.826

In [4]:
nasa_data.head()

,rowid,kepid,kepoi_name,kepler_name,koi_disposition,koi_pdisposition,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,...,koi_steff_err2,koi_slogg,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag
0,1,10797460,K00752.01,Kepler-227 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
1,2,10797460,K00752.02,Kepler-227 c,CONFIRMED,CANDIDATE,0.969,0,0,0,...,-81.0,4.467,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347
2,3,10811496,K00753.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-176.0,4.544,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436
3,4,10848459,K00754.01,NaN,FALSE POSITIVE,FALSE POSITIVE,0.000,0,1,0,...,-174.0,4.564,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597
4,5,10854555,K00755.01,Kepler-664 b,CONFIRMED,CANDIDATE,1.000,0,0,0,...,-211.0,4.438,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509

In [5]:
nasa_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9564 entries, 0 to 9563
Data columns (total 50 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   rowid              9564 non-null   int64
 1   kepid              9564 non-null   int64
 2   kepoi_name         9564 non-null   object
 3   kepler_name        2294 non-null   object
 4   koi_disposition    9564 non-null   object
 5   koi_pdisposition   9564 non-null   object
 6   koi_score          8054 non-null   float64
 7   koi_fpflag_nt      9564 non-null   int64
 8   koi_fpflag_ss      9564 non-null   int64
 9   koi_fpflag_co      9564 non-null   int64
 10  koi_fpflag_ec      9564 non-null   int64
 11  koi_period         9564 non-null   float64
 12  koi_period_err1    9110 non-null   float64
 13  koi_period_err2    9110 non-null   float64
 14  koi_time0bk        9564 non-null   float64
 15  koi_time0bk_err1   9110 non-null   float64
 16  koi_time0bk_err2   9110 non-null   float64
 17  koi_impact         9201 non-null   float64
 18  koi_impact_err1    9110 non-null   float64
 19  koi_impact_err2    9110 non-null   float64
 20  koi_duration       9564 non-null   float64
 21  koi_duration_err1  9110 non-null   float64
 22  koi_duration_err2  9110 non-null   float64
 23  koi_depth          9201 non-null   float64
 24  koi_depth_err1     9110 non-null   float64
 25  koi_depth_err2     9110 non-null   float64
 26  koi_prad           9201 non-null   float64
 27  koi_prad_err1      9201 non-null   float64
 28  koi_prad_err2      9201 non-null   float64
 29  koi_teq            9201 non-null   float64
 30  koi_teq_err1       0 non-null      float64
 31  koi_teq_err2       0 non-null      float64
 32  koi_insol          9243 non-null   float64
 33  koi_insol_err1     9243 non-null   float64
 34  koi_insol_err2     9243 non-null   float64
 35  koi_model_snr      9201 non-null   float64
 36  koi_tce_plnt_num   9218 non-null   float64
 37  koi_tce_delivname  9218 non-null   object
 38  koi_steff          9201 non-null   float64
 39  koi_steff_err1     9096 non-null   float64
 40  koi_steff_err2     9081 non-null   float64
 41  koi_slogg          9201 non-null   float64
 42  koi_slogg_err1     9096 non-null   float64
 43  koi_slogg_err2     9096 non-null   float64
 44  koi_srad           9201 non-null   float64
 45  koi_srad_err1      9096 non-null   float64
 46  koi_srad_err2      9096 non-null   float64
 47  ra                 9564 non-null   float64
 48  dec                9564 non-null   float64
 49  koi_kepmag         9563 non-null   float64
dtypes: float64(39), int64(6), object(5)
memory usage: 3.6+ MB

In [6]:
nasa_data["label"] = nasa_data["koi_pdisposition"].apply(
    lambda x: 1 if x == "CANDIDATE" else 0
)
nasa_data["label_2"] = nasa_data["koi_disposition"].apply(
    lambda x: 2 if x == "CONFIRMED" else 1 if x == "CANDIDATE" else 0
)

In [7]:
nasa_data.drop(columns=['kepler_name','rowid','kepid','kepoi_name','koi_teq_err1','koi_teq_err2','koi_disposition','koi_pdisposition','koi_tce_delivname'], inplace=True)

In [8]:
nasa_data.dropna(inplace=True)

In [9]:
nasa_data.head()

,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag,lable,lable_2
0,1.000,0,0,0,0,9.488036,2.775000e-05,-2.775000e-05,170.538750,0.002160,...,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1,2
1,0.969,0,0,0,0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,...,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1,2
2,0.000,0,1,0,0,19.899140,1.494000e-05,-1.494000e-05,175.850252,0.000581,...,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436,0,0
3,0.000,0,1,0,0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597,0,0
4,1.000,0,0,0,0,2.525592,3.761000e-06,-3.761000e-06,171.595550,0.001130,...,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509,1,2

In [10]:
def clean_dataset(df):
    assert isinstance(nasa_data, pd.DataFrame),nasa_data.dropna(inplace=True)
    indices = ~nasa_data.isin([np.nan, np.inf, -np.inf]).any(1)
    return nasa_data[indices].astype(np.float64)

clean_dataset(nasa_data)

,koi_score,koi_fpflag_nt,koi_fpflag_ss,koi_fpflag_co,koi_fpflag_ec,koi_period,koi_period_err1,koi_period_err2,koi_time0bk,koi_time0bk_err1,...,koi_slogg_err1,koi_slogg_err2,koi_srad,koi_srad_err1,koi_srad_err2,ra,dec,koi_kepmag,lable,lable_2
0,1.000,0.0,0.0,0.0,0.0,9.488036,2.775000e-05,-2.775000e-05,170.538750,0.002160,...,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1.0,2.0
1,0.969,0.0,0.0,0.0,0.0,54.418383,2.479000e-04,-2.479000e-04,162.513840,0.003520,...,0.064,-0.096,0.927,0.105,-0.061,291.93423,48.141651,15.347,1.0,2.0
2,0.000,0.0,1.0,0.0,0.0,19.899140,1.494000e-05,-1.494000e-05,175.850252,0.000581,...,0.044,-0.176,0.868,0.233,-0.078,297.00482,48.134129,15.436,0.0,0.0
3,0.000,0.0,1.0,0.0,0.0,1.736952,2.630000e-07,-2.630000e-07,170.307565,0.000115,...,0.053,-0.168,0.791,0.201,-0.067,285.53461,48.285210,15.597,0.0,0.0
4,1.000,0.0,0.0,0.0,0.0,2.525592,3.761000e-06,-3.761000e-06,171.595550,0.001130,...,0.070,-0.210,1.046,0.334,-0.133,288.75488,48.226200,15.509,1.0,2.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
9559,0.000,0.0,0.0,0.0,1.0,8.589871,1.846000e-04,-1.846000e-04,132.016100,0.015700,...,0.231,-0.189,1.088,0.313,-0.228,298.74921,46.973351,14.478,0.0,0.0
9560,0.000,0.0,1.0,1.0,0.0,0.527699,1.160000e-07,-1.160000e-07,131.705093,0.000170,...,0.035,-0.196,0.903,0.237,-0.079,297.18875,47.093819,14.082,0.0,0.0
9561,0.497,0.0,0.0,0.0,0.0,1.739849,1.780000e-05,-1.780000e-05,133.001270,0.007690,...,0.056,-0.224,1.031,0.341,-0.114,286.50937,47.163219,14.757,1.0,1.0
9562,0.021,0.0,0.0,1.0,0.0,0.681402,2.434000e-06,-2.434000e-06,132.181750,0.002850,...,0.056,-0.224,1.041,0.341,-0.114,294.16489,47.176281,15.385,0.0,0.0
9563,0.000,0.0,0.0,1.0,1.0,4.856035,6.356000e-05,-6.356000e-05,135.993300,0.010800,...,0.054,-0.216,1.193,0.410,-0.137,297.00977,47.121021,14.826,0.0,0.0

In [11]:
x_data = nasa_data.drop(columns=['label','label_2'])
y_label_1 = nasa_data.label
y_label_2 = nasa_data.label_2

In [12]:
X_train, X_test, y_train, y_test = train_test_split(x_data, y_label_1, random_state=0, test_size=.40)

In [13]:
print(len(X_train))
print(len(y_train))
print(len(X_test))
print(len(y_test))

4681
4681
3122
3122

In [14]:
bagging_model = BaggingClassifier(base_estimator=RandomForestClassifier(n_estimators=100,criterion='gini'),n_estimators=10, random_state=0)
bagging_model.fit(X_train,y_train)
y_pred_bagging = bagging_model.predict(X_test)

In [15]:
print('Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred_bagging)))
print('\nConfusion Matrix:')
print(' TN,  FP, FN, TP')
clf_b = confusion_matrix(y_test, y_pred_bagging).ravel()
print(clf_b)

Accuracy: 0.9967969250480462

Confusion Matrix:
 TN,  FP, FN, TP
[1547    2    8 1565]

In [16]:
randf = RandomForestClassifier(n_estimators=100, criterion='gini')
randf.fit(X_train, y_train)
y_pred_forest = randf.predict(X_test)

In [17]:
print('Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred_forest)))
print('\nConfusion Matrix:')
print(' TN,  FP, FN, TP')
clf_rf = confusion_matrix(y_test, y_pred_forest).ravel()
print(clf_rf)

Accuracy: 0.9948750800768738

Confusion Matrix:
 TN,  FP, FN, TP
[1543    6   10 1563]

In [18]:
tree = DecisionTreeClassifier()
tree.fit(X_train, y_train)
y_pred_tree = tree.predict(X_test)

In [19]:
print('Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred_tree)))
print('\nConfusion Matrix:')
print(' TN,  FP, FN, TP')
clf_dt = confusion_matrix(y_test, y_pred_tree).ravel()
print(clf_dt)

Accuracy: 0.9948750800768738

Confusion Matrix:
 TN,  FP, FN, TP
[1536   13    3 1570]

In [25]:
window = Tk()
window.title('Models comparison')
window.geometry("1200x900")
window.configure(bg='black')
window.resizable(True,True)

##############################
bagging_label = Label(window, bg="white", font=("Courier", 20, "bold"), relief="flat")
bagging_label.place(x=10,y=10)
bagging_label.configure(text="BAGGING CLASSIFIER")

bagging_text = 'Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred_bagging)) + '\nConfusion Matrix:' + '\nTN,  FP, FN, TP' + '\n' + str(confusion_matrix(y_test, y_pred_bagging).ravel())

bagging_score = Label(window, bg="white", font=("Courier", 14), relief="flat")
bagging_score.place(x=100,y=100)
bagging_score.configure(text=bagging_text)

##############################

rf_label = Label(window, bg="white", font=("Courier", 20, "bold"), relief="flat")
rf_label.place(x=10,y=300)
rf_label.configure(text="RANDOM FOREST CLASSIFIER")

rf_text = 'Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred_forest)) + '\nConfusion Matrix:' + '\nTN,  FP, FN, TP' + '\n' + str(confusion_matrix(y_test, y_pred_forest).ravel())

rf_score = Label(window, bg="white", font=("Courier", 14), relief="flat")
rf_score.place(x=100,y=390)
rf_score.configure(text=rf_text)

##############################

dt_label = Label(window, bg="white", font=("Courier", 20, "bold"), relief="flat")
dt_label.place(x=10,y=600)
dt_label.configure(text="DECISION TREE CLASSIFIER")

dt_text = 'Accuracy: ' + str(metrics.accuracy_score(y_test, y_pred_tree)) + '\nConfusion Matrix:' + '\nTN,  FP, FN, TP' + '\n' + str(confusion_matrix(y_test, y_pred_tree).ravel())

dt_score = Label(window, bg="white", font=("Courier", 14), relief="flat")
dt_score.place(x=100,y=690)
dt_score.configure(text=dt_text)

##############################

window.mainloop()